# NumPy
### **Задание на повторение материала
##### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [3]:
import numpy as np

In [62]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

##### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [74]:
array1 = a.reshape((6, 2), order='C')[2:4]
array1

array([[16, 17],
       [18, 19]])

In [75]:
array2 = a.reshape((6, 2), order='C')[3:]
array2

array([[18, 19],
       [20, 21],
       [22, 23]])

In [76]:
array3 = a.reshape((2, 6), order='C')[:,:3]
array3

array([[12, 13, 14],
       [18, 19, 20]])

In [84]:
array4 = a.reshape((3, 4), order='F')[:2]
array4

array([[12, 15, 18, 21],
       [13, 16, 19, 22]])

In [85]:
array5 = a.reshape((6, 2), order='F')
array5

array([[12, 18],
       [13, 19],
       [14, 20],
       [15, 21],
       [16, 22],
       [17, 23]])

##### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [79]:
array6 = a.reshape((6, -1), order='C')[2:4]
array6

array([[16, 17],
       [18, 19]])

In [80]:
array7 = a.reshape((6, -1), order='C')[3:]
array7

array([[18, 19],
       [20, 21],
       [22, 23]])

In [81]:
array8 = a.reshape((2, -1), order='C')[:,:3]
array8

array([[12, 13, 14],
       [18, 19, 20]])

In [86]:
array9 = a.reshape((-1, 4), order='F')[:2]
array9

array([[12, 15, 18, 21],
       [13, 16, 19, 22]])

In [96]:
array10 = a.reshape((-1, 2), order='F')
array10

array([[12, 18],
       [13, 19],
       [14, 20],
       [15, 21],
       [16, 22],
       [17, 23]])

##### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [99]:
# С точки зрения математики можно, но обращение в NumPy будет по 2м индексам, как к двумерному массиву
a.reshape(12,1).shape

(12, 1)

##### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [32]:
new_array = np.random.randn(3, 4)
new_array

array([[ 0.47128928,  0.91145474,  0.92150441, -0.11110338],
       [-3.29215266, -0.9870213 , -0.57372777, -0.85708841],
       [ 0.68569025, -1.00177817, -1.58247187, -0.9513045 ]])

In [72]:
new_array2 = new_array.flatten()
new_array2

array([ 0.47128928,  0.91145474,  0.92150441, -0.11110338, -3.29215266,
       -0.9870213 , -0.57372777, -0.85708841,  0.68569025, -1.00177817,
       -1.58247187, -0.9513045 ])

In [37]:
new_array.size == new_array2.size

True

##### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [57]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [75]:
a.shape

(10,)

##### 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [7]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [14]:
# С точки зрения математики, разницы никакой. Но судя по форме, в numpy он воспринимается несколько иначе,
# а именно: "a" - выглядит как последовательность 10-ти элементов (10,), "b" - явный массив размером (1, 10)
b.shape

(1, 10)

##### 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [96]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [97]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [98]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [99]:
v.size

10

##### 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [101]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [102]:
A = np.reshape(a, (4, 3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [103]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [105]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

##### 10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [140]:
np.random.seed(42)

##### 11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [145]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  1,  3,  8, 11, 13,  1,  9,  8,  9,  4,  1,  3, 11, 14, 11])

##### 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [146]:
C = np.reshape(c, (4, 4))
C

array([[ 6,  1,  3,  8],
       [11, 13,  1,  9],
       [ 8,  9,  4,  1],
       [ 3, 11, 14, 11]])

In [161]:
D = B + np.dot(C, 10)
D

array([[ 65,  24,  53, 112],
       [124, 180,  96, 212],
       [103, 176, 189, 222],
       [ 62, 232, 352, 412]])

In [162]:
np.linalg.det(D)

171262000.00000015

In [163]:
np.linalg.matrix_rank(D)

4

In [181]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 1.03443846e-02, -5.29948266e-03,  1.42261564e-02,
        -7.75069776e-03],
       [-1.41030701e-02,  7.06928566e-03,  4.01490115e-04,
        -2.00861837e-05],
       [ 1.14818232e-03, -1.24464271e-02,  1.56770329e-02,
        -2.35498826e-03],
       [ 5.40388411e-03,  7.45057281e-03, -1.57608810e-02,
         5.61689108e-03]])

In [176]:
# проверка обратной матрицы, должна получиться единичная матрица E
np.around(np.dot(D, D_inv))

array([[ 1., -0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1., -0.],
       [ 0.,  0.,  0.,  1.]])

##### 13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [182]:
D_inv[D_inv>0] = 1
D_inv[D_inv<0] = 0
D_inv

array([[1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 1.]])

In [184]:
E = np.where([D_inv], B, C)
E

array([[[  5,   1,  23,   8],
        [ 11,  50,  86,   9],
        [ 23,   9, 149,   1],
        [ 32, 122,  14, 302]]])